workflows:
  ios-workflow:
    name: iOS Build - video
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: video
        FLUTTER: "false"        # يجب أن يكون string وليس boolean
        XCODE: "14.0"
        COCOAPODS: "true"       # string بدل boolean
        APPLE_ID: $APPLE_ID
        APP_SPECIFIC_PASSWORD: $APP_SPECIFIC_PASSWORD
    scripts:
      - name: Install dependencies
        script: |
          if [ "${COCOAPODS}" = "true" ]; then
            pod install --repo-update || true
          fi
    triggering:
      events:
        - push
        - pull_request
    builds:
      ios:
        scheme: video
        export_method: development
        build_configuration: Release
