
workflows:
  ios-workflow:
    name: iOS Build - video
    max_build_duration: 60
    environment:
      flutter: false
      xcode: "14.0"          # عدّل حسب نسخة Xcode المتوفرة لديك
      cocoapods: true         # إذا تستخدم CocoaPods، غيره إلى false إذا لا تستخدم
      vars:
        APP_NAME: video
    scripts:
      - name: Install dependencies
        script: pod install --repo-update || true
    triggers:
      - push
      - pull_request
    ios:
      scheme: video            # اسم Scheme في Xcode
      export_method: development  # لأن الحساب مجاني
      build_configuration: Release
      signing:
        apple_id: $APPLE_ID             # Apple ID الخاص بك كمتغير بيئة
        password: $APP_SPECIFIC_PASSWORD # كلمة سر التطبيق الخاصة (App-Specific Password)
